version: '2'

services:
    application:
        container_name: unic_application
        image: debian
        volumes:
            - ./:/var/www/laravel
    workspace:
        container_name: unic_workspace
        image: tranvanmy/laravel-workspace
        volumes_from:
            - application
        tty: true
    php-fpm:
        container_name: unic_php-fpm
        image: tranvanmy/laravel-php-fpm
        volumes_from:
            - application
        expose:
            - "2222"
        links:
            - workspace
    nginx:
        container_name: unic_nginx
        image: tranvanmy/laravel-nginx
        volumes_from:
            - data
            - logs
            - application
        ports:
            - "2025:80"
        links:
            - php-fpm
    data:
        container_name: unic_data
        image: debian
        volumes:
            - .docker/mysql:/var/lib/mysql
            - .docker/data:/data
    logs:
        container_name: unic_logs
        image: debian
        volumes:
            - .docker/logs/nginx:/var/log/nginx
            - .docker/logs/mongodb:/var/log/mongodb
    redis:
        container_name: unic_redis
        image: redis
        expose:
            - "6379"
        volumes_from:
            - data
