version: '2'

services:
    application:
        container_name: fsc_production_application
        restart: always
    workspace:
        container_name: fsc_production_workspace
        restart: always
    php-fpm:
        container_name: fsc_production_php-fpm
        restart: always
    nginx:
        container_name: fsc_production_nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
    data:
        container_name: fsc_production_data
        restart: always
    logs:
        container_name: fsc_production_logs
        restart: always
    redis:
        container_name: fsc_production_redis
        restart: always
